In [1]:
import numpy as np

In [14]:
def Change_Nan(a):
    for i in range(a.shape[1]): #遍历每一列
        temp_col = a[:,i] #当前这一列
        nan_number = np.count_nonzero(temp_col!=temp_col) #判断当前列是否有nan
        if nan_number != 0:
            temp_not_nan_col = temp_col[temp_col==temp_col]
            temp_col[np.isnan(temp_col)] = temp_not_nan_col.mean()
            
    return a
a = np.arange(24).reshape(4,6).astype(float)
a[1,2:] = np.nan
print(a)
print()
Change_Nan(a)
print(a)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7. nan nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7. 12. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
