In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False

In [2]:
# 一、线性回归




In [3]:
# 练习1.通过身高预测体重（一元回归）
model = linear_model.LinearRegression()

data = pd.read_excel('./挖掘建模data/身高体重.xls')

model.fit(data['身高'].values.reshape(-1,1),data['体重'].values.reshape(-1,1))

model.predict([[1.75]])

array([[62.83640738]])

In [4]:
# 练习2.通过日期预测销量（二元回归）
data = pd.read_excel('./挖掘建模data/arima_data.xls')

X = np.array(data.index).reshape(-1,1) #日期是字符串，要转换成数字，但过于麻烦，故选择index
y = data['销量'].values.reshape(-1,1) #将其变为2维

model.fit(X,y)

print(model.predict([[37]])) #要使用2维数据预测
print()
print(model.coef_) #线性回归系数k
print()
print(model.intercept_) #线性回归常识b

[[4400.48198198]]

[[45.15765766]]

[2729.64864865]


In [5]:
# 练习3.通过广告费用和人口数预测产品销售量（二元回归）
data = pd.read_excel('./挖掘建模data/广告.xls')

X = data[['广告费用X1（万元）','人口数X2（万人）']].values
y = data['产品销售量Y（万件）'].values

model.fit(X,y)

model.predict([[375,9]])

array([45926.39538257])

In [6]:
# 练习4.预测y值（多元回归）
data = pd.read_excel('./挖掘建模data/财政收入影响.xls')

X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values.reshape(-1,1)

Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,y,test_size=0.3,random_state=420)

model.fit(Xtrain,Ytrain)

print(model.predict(Xtest))
print()
print(model.score(Xtrain,Ytrain))

[[ 673.35410919]
 [-262.55682309]
 [1031.89185574]
 [-343.48270858]
 [ 213.6064129 ]
 [ 179.84185587]]

1.0


In [7]:
# 二、逻辑回归




