In [65]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier as MLP
from sklearn.metrics import accuracy_score
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False

In [66]:
# 一、线性回归




In [67]:
# 练习1.通过身高预测体重（一元回归）
model = linear_model.LinearRegression()

data = pd.read_excel('./挖掘建模data/身高体重.xls')

model.fit(data['身高'].values.reshape(-1,1),data['体重'].values.reshape(-1,1))

model.predict([[1.75]])

array([[62.83640738]])

In [68]:
# 练习2.通过日期预测销量（二元回归）
data = pd.read_excel('./挖掘建模data/arima_data.xls')

X = np.array(data.index).reshape(-1,1) #日期是字符串，要转换成数字，但过于麻烦，故选择index
y = data['销量'].values.reshape(-1,1) #将其变为2维

model.fit(X,y)

print(model.predict([[37]])) #要使用2维数据预测
print()
print(model.coef_) #线性回归系数k
print()
print(model.intercept_) #线性回归常识b

[[4400.48198198]]

[[45.15765766]]

[2729.64864865]


In [69]:
# 练习3.通过广告费用和人口数预测产品销售量（二元回归）
data = pd.read_excel('./挖掘建模data/广告.xls')

X = data[['广告费用X1（万元）','人口数X2（万人）']].values
y = data['产品销售量Y（万件）'].values

model.fit(X,y)

model.predict([[375,9]])

array([45926.39538257])

In [70]:
# 练习4.预测y值（多元回归）
data = pd.read_excel('./挖掘建模data/财政收入影响.xls')

X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values.reshape(-1,1)

Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,y,test_size=0.3,random_state=420)

model.fit(Xtrain,Ytrain)

print(model.predict(Xtest))
print()
print(model.score(Xtrain,Ytrain))

[[ 673.35410919]
 [-262.55682309]
 [1031.89185574]
 [-343.48270858]
 [ 213.6064129 ]
 [ 179.84185587]]

1.0


In [71]:
# 二、逻辑回归






In [72]:
df = pd.read_excel('./挖掘建模data/bankloan.xls')

In [73]:
df.head()

年龄  教育  工龄  地址   收入   负债率      信用卡负债      其他负债  违约
0  41   3  17  12  176   9.3  11.359392  5.008608   1
1  27   1  10   6   31  17.3   1.362202  4.000798   0
2  40   1  15  14   55   5.5   0.856075  2.168925   0
3  41   1  15  14  120   2.9   2.658720  0.821280   0
4  24   2   2   0   28  17.3   1.787436  3.056564   1

In [74]:
from sklearn.linear_model import LogisticRegression as LR

In [75]:
lr = LR()
data = df.values
X = data[:,:-1]
y = data[:,-1]
lr.fit(X,y)
lr.score(X,y)

D:\Anconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8057142857142857

In [76]:
df = pd.read_excel('./挖掘建模data/西瓜数据.xlsx',index_col='编号')

In [77]:
df1 = df[['色泽','根蒂','敲声','纹理','脐部','触感','好瓜']]

In [78]:
df1['色泽'].replace({"浅白":1,"青绿":2,"乌黑":3},inplace = True)
df1['根蒂'].replace({"蜷缩":1,"稍蜷":2,"硬挺":3},inplace = True)
df1['敲声'].replace({"沉闷":1,"浊响":2,"清脆":3},inplace = True)
df1['纹理'].replace({"模糊":1,"稍糊":2,"清晰":3},inplace = True)
df1['脐部'].replace({"凹陷":1,"稍凹":2,"平坦":3},inplace = True)
df1['触感'].replace({"软粘":1,"硬滑":2},inplace = True)

D:\Anconda\lib\site-packages\pandas\core\generic.py:6586: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [79]:
df1

色泽  根蒂  敲声  纹理  脐部  触感  好瓜
编号                            
5    1   1   2   3   1   2   1
11   1   3   3   1   3   2   0
12   1   1   2   1   3   1   0
14   1   2   1   2   1   2   0
16   1   1   2   1   3   2   0
1    2   1   2   3   1   2   1
4    2   1   1   3   1   2   1
6    2   2   2   3   2   1   1
10   2   3   3   3   3   1   0
13   2   2   2   2   1   2   0
17   2   1   1   2   2   2   0
2    3   1   1   3   1   2   1
3    3   1   2   3   1   2   1
7    3   2   2   2   2   1   1
8    3   2   2   3   2   2   1
9    3   2   1   2   2   2   0
15   3   2   2   3   2   1   0

In [80]:
dfs = df1.values
X = dfs[:,:-1]
y = dfs[:,-1]
lr.fit(X,y)
lr.score(X,y)

D:\Anconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8823529411764706

In [81]:
df1.corr('spearman')

色泽        根蒂        敲声        纹理        脐部        触感        好瓜
色泽  1.000000  0.098566 -0.204052  0.486772 -0.211665 -0.111752  0.369805
根蒂  0.098566  1.000000  0.448543 -0.106904  0.395128 -0.347691 -0.357071
敲声 -0.204052  0.448543  1.000000 -0.032275  0.500629 -0.404881 -0.082134
纹理  0.486772 -0.106904 -0.032275  1.000000 -0.507814 -0.058078  0.662718
脐部 -0.211665  0.395128  0.500629 -0.507814  1.000000 -0.492662 -0.526834
触感 -0.111752 -0.347691 -0.404881 -0.058078 -0.492662  1.000000  0.091287
好瓜  0.369805 -0.357071 -0.082134  0.662718 -0.526834  0.091287  1.000000

In [82]:
#三、决策树





In [83]:
from sklearn import tree
from sklearn.model_selection import train_test_split

In [84]:
data = pd.read_excel('./挖掘建模data/bankloan.xls')

In [85]:
data.head()

年龄  教育  工龄  地址   收入   负债率      信用卡负债      其他负债  违约
0  41   3  17  12  176   9.3  11.359392  5.008608   1
1  27   1  10   6   31  17.3   1.362202  4.000798   0
2  40   1  15  14   55   5.5   0.856075  2.168925   0
3  41   1  15  14  120   2.9   2.658720  0.821280   0
4  24   2   2   0   28  17.3   1.787436  3.056564   1

In [86]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(data.iloc[:,:-1].values,data.iloc[:,-1].values,test_size=0.43)

In [87]:
clf = tree.DecisionTreeClassifier(criterion="entropy",random_state=30)
clf = clf.fit(Xtrain, Ytrain)
score = clf.score(Xtest, Ytest) #返回预测的准确度
score

0.717607973421927

In [88]:
#四、人工神经网络




In [89]:
model = MLP((100,100,100))
df = data.values
X = df[:,:-1]
y = df[:,-1]
Xtrain, Xtest, Ytrain, Ytest = X[400:], X[:400], y[400:], y[:400]
model.fit(Xtrain,Ytrain)
print(model.score(Xtrain,Ytrain))
y_pred = model.predict(Xtest)
print(accuracy_score(y_pred,Ytest))

0.9366666666666666
0.7525


D:\Anconda\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [90]:
y_pred = model.predict(Xtest)
print(accuracy_score(y_pred,Ytest))

0.7525
