In [1]:
import numpy as np

In [2]:
a = np.arange(1,25).reshape(4,6)

In [3]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [4]:
a = a.astype(float)

In [5]:
a[3,4] = np.nan

In [6]:
a

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., nan, 24.]])

In [7]:
np.nan == np.nan

False

In [8]:
a[:,0] = 0

In [9]:
a

array([[ 0.,  2.,  3.,  4.,  5.,  6.],
       [ 0.,  8.,  9., 10., 11., 12.],
       [ 0., 14., 15., 16., 17., 18.],
       [ 0., 20., 21., 22., nan, 24.]])

In [10]:
np.count_nonzero(a) #判断非0数个数

20

In [11]:
np.count_nonzero(a!=a) #判断nan个数

1

In [12]:
np.isnan(a) #判断是否有nan

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False]])

In [13]:
a[np.isnan(a)] = 0

In [14]:
a

array([[ 0.,  2.,  3.,  4.,  5.,  6.],
       [ 0.,  8.,  9., 10., 11., 12.],
       [ 0., 14., 15., 16., 17., 18.],
       [ 0., 20., 21., 22.,  0., 24.]])

In [15]:
a[3,4] = np.nan

In [16]:
a

array([[ 0.,  2.,  3.,  4.,  5.,  6.],
       [ 0.,  8.,  9., 10., 11., 12.],
       [ 0., 14., 15., 16., 17., 18.],
       [ 0., 20., 21., 22., nan, 24.]])

In [17]:
a+3 #nan和任何数计算都是nan

array([[ 3.,  5.,  6.,  7.,  8.,  9.],
       [ 3., 11., 12., 13., 14., 15.],
       [ 3., 17., 18., 19., 20., 21.],
       [ 3., 23., 24., 25., nan, 27.]])

In [18]:
np.sum(a)

nan

In [19]:
b = np.arange(12).reshape(3,4)

In [20]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
b.sum(axis=0) #axis= 0 对a的横轴进行操作，在运算的过程中其运算的方向表现为纵向运算

array([12, 15, 18, 21])

In [22]:
b.sum(axis=1) #axis= 1 对a的纵轴进行操作，在运算的过程中其运算的方向表现为横向运算

array([ 6, 22, 38])