In [1]:
import numpy as np

In [2]:
#本地数据读取
us_data = "./youtube_video_data/US_video_data_numbers.csv"

uk_data = "./youtube_video_data/GB_video_data_numbers.csv"

In [3]:
us_data = np.loadtxt(us_data,delimiter=",",dtype="int")

uk_data = np.loadtxt(uk_data,delimiter=",",dtype="int")

In [4]:
#拼接






In [5]:
#stack,hstack,vstack

#添加国家信息
#构造全为0和1的数据
zeros_data = np.zeros((us_data.shape[0],1)).astype(int)
ones_data = np.ones((uk_data.shape[0],1)).astype(int)

#分别添加一列全为1,0的数组
us_data = np.hstack((us_data,zeros_data)) #hstack为水平拼接,np.stack((us_data,zeros_data),1)
uk_data = np.hstack((uk_data,ones_data))

#拼接两组数据()
final_data = np.vstack((us_data,uk_data)) #vstack为竖直拼接,np.stack((us_data,uk_data),0)

In [6]:
final_data

array([[4394029,  320053,    5931,   46245,       0],
       [7860119,  185853,   26679,       0,       0],
       [5845909,  576597,   39774,  170708,       0],
       ...,
       [ 109222,    4840,      35,     212,       1],
       [ 626223,   22962,     532,    1559,       1],
       [  99228,    1699,      23,     135,       1]])

In [7]:
#concatenate
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print()
print(b)
print()
print(np.concatenate((a,b),axis=0))
print()
print(np.concatenate((a,b),axis=1))

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [8]:
#分割






In [9]:
#split
a = np.arange(9)
print(a)
print()
print(np.split(a,3)) #均等三份
print()
print(np.split(a,[4,7])) #表明位置分割
print()

print(b)
print()
#hsplit,横轴分割
b = np.arange(24).reshape(4,6)
print(np.hsplit(b,2))
print()

#vsplit，竖轴分割
print(np.vsplit(b,2))
print()

[0 1 2 3 4 5 6 7 8]

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

[[5 6]
 [7 8]]

[array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]]), array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])]

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])]



In [10]:
#行列交换






In [11]:
#行交换
final_data[[1,2],:] = final_data[[2,1],:] 

In [12]:
final_data

array([[4394029,  320053,    5931,   46245,       0],
       [5845909,  576597,   39774,  170708,       0],
       [7860119,  185853,   26679,       0,       0],
       ...,
       [ 109222,    4840,      35,     212,       1],
       [ 626223,   22962,     532,    1559,       1],
       [  99228,    1699,      23,     135,       1]])

In [13]:
# 列交换
final_data[:,[0,2]] = final_data[:,[2,0]]

In [14]:
final_data

array([[   5931,  320053, 4394029,   46245,       0],
       [  39774,  576597, 5845909,  170708,       0],
       [  26679,  185853, 7860119,       0,       0],
       ...,
       [     35,    4840,  109222,     212,       1],
       [    532,   22962,  626223,    1559,       1],
       [     23,    1699,   99228,     135,       1]])