In [1]:
import numpy as np

In [2]:
#本地数据读取
us_file_path = "./youtube_video_data/US_video_data_numbers.csv"

uk_file_path = "./youtube_video_data/GB_video_data_numbers.csv"

In [3]:
t1 = np.loadtxt(us_file_path,delimiter=",",dtype="int",unpack=True) #unpack默认为False，True为转置

t2 = np.loadtxt(us_file_path,delimiter=",",dtype="int")

In [4]:
t1

array([[4394029, 7860119, 5845909, ...,  142463, 2162240,  515000],
       [ 320053,  185853,  576597, ...,    4231,   41032,   34727],
       [   5931,   26679,   39774, ...,     148,    1384,     195],
       [  46245,       0,  170708, ...,     279,    4737,    4722]])

In [5]:
t2

array([[4394029,  320053,    5931,   46245],
       [7860119,  185853,   26679,       0],
       [5845909,  576597,   39774,  170708],
       ...,
       [ 142463,    4231,     148,     279],
       [2162240,   41032,    1384,    4737],
       [ 515000,   34727,     195,    4722]])

In [6]:
#转置的三种方法
x = np.arange(24).reshape(4,6)

x1 = x.transpose()
x2 = x.T
x3 = x.swapaxes(1,0)
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [7]:
x1

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [8]:
x2

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [9]:
x3

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])