In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False

In [2]:
# 1.降维与主成分分析




In [3]:
data = pd.read_excel('../实验数据/城市经济指标分析.xls',index_col=0)

In [4]:
data.head()

人均GDP  新增固定资产  城镇居民人均年可支配收入  农村居民机家庭纯收入  高等学校数量  卫生机构数量
地区                                                               
上 海       15204  128.93          7191        4245      45    5286
北 京       10265   30.81          6235        3223      65    4955
天 津        8164   49.13          4929        2406      21    3182
广 东        6380   51.82          7438        2699      42    8848
浙 江        6149   41.88          6221        2966      37    8721

In [5]:
pca = PCA()
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [6]:
pca.components_ #查看新旧指标对应关系

array([[-1.09987691e-01,  4.80909247e-03,  2.43226961e-02,
         4.10228391e-03,  3.45773926e-03,  9.93609180e-01],
       [ 9.13415352e-01,  5.46296915e-03,  3.13244095e-01,
         2.42852236e-01,  2.14159713e-03,  9.24061296e-02],
       [-3.42659686e-01, -1.73950883e-02,  9.30559819e-01,
         1.12195451e-01, -4.74274724e-03, -6.10725790e-02],
       [-1.89766941e-01, -8.86487255e-03, -1.87487724e-01,
         9.63446240e-01,  1.06732600e-02, -2.03887248e-02],
       [-1.21513412e-02,  9.98423294e-01,  1.29774789e-02,
         8.59935465e-03,  5.21138703e-02, -6.71202369e-03],
       [-5.43101494e-04, -5.21227323e-02,  4.99042783e-03,
        -1.07488487e-02,  9.98564565e-01, -3.36061022e-03]])

In [7]:
pca.explained_variance_ #查看降维后每个新特征向量上所带的信息量大小（可解释性方差的大小）

array([1.35028294e+07, 9.71394734e+06, 4.96242026e+05, 4.26027446e+04,
       3.67620273e+02, 8.95640940e+01])

In [8]:
np.cumsum(pca.explained_variance_ratio_) #查看降维后每个新特征向量所占的信息量占原始数据总信息量的百分比

array([0.56839471, 0.97729836, 0.99818741, 0.99998076, 0.99999623,
       1.        ])

In [9]:
#取前两个坐标系
pca = PCA(2)
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [10]:
pca.components_ #V(k,n)

array([[-0.10998769,  0.00480909,  0.0243227 ,  0.00410228,  0.00345774,
         0.99360918],
       [ 0.91341535,  0.00546297,  0.31324409,  0.24285224,  0.0021416 ,
         0.09240613]])

In [11]:
newdata = pca.transform(data)
data1 = pd.DataFrame(newdata,index=data.index,columns=['公共服务','经济收入'])
data1.head()

公共服务          经济收入
地区                                 
上 海      -2328.926674  11318.965632
北 京      -2142.429853   6228.871245
天 津      -3708.195835   3538.448310
广 东       2180.124981   3289.633260
浙 江       2050.773270   2750.457209

In [12]:
data1.mean(axis=1).sort_values(ascending=False)

地区
四 川         5862.817813
上 海         4495.019479
江 苏         3725.646247
广 东         2734.879121
浙 江         2400.615239
山 东         2188.825385
北 京         2043.220696
河 北         1577.346598
湖 北         1308.711227
湖 南          794.264151
辽 宁          721.626420
黑龙江          491.750321
天 津          -84.873763
河 南         -358.099810
福 建         -580.792537
安 徽         -827.191919
云 南         -934.331223
广 西        -1095.568239
山 西        -1166.534023
陕 西        -1227.683516
江 西        -1562.624973
新 疆        -1662.685470
内蒙古        -1709.679658
吉 林        -1886.596562
海 南        -2402.324905
甘 肃        -2564.393793
贵 州        -2663.834133
青 海        -3726.791200
宁 夏        -3890.716972
dtype: float64

In [13]:
(data1 * [0.3,0.7]).sum(axis=1).sort_values(ascending=False)

地区
上 海         7224.597940
北 京         3717.480916
四 川         3212.627095
江 苏         3076.984648
广 东         2956.780776
浙 江         2540.552027
山 东         1498.924294
天 津         1364.455066
辽 宁         1009.889073
河 北          676.351045
湖 北          503.717190
黑龙江          252.854478
福 建           14.163893
湖 南           -8.050787
河 南        -1030.795997
广 西        -1234.290042
安 徽        -1265.922669
新 疆        -1319.039578
云 南        -1340.903568
海 南        -1417.087845
山 西        -1456.227276
吉 林        -1617.615143
陕 西        -1678.836684
内蒙古        -1803.603202
江 西        -1833.146063
甘 肃        -2738.668202
贵 州        -2823.892247
青 海        -3150.078248
宁 夏        -3331.220892
dtype: float64

In [14]:
# 统一量纲
from sklearn.preprocessing import MinMaxScaler
model = MinMaxScaler()
std_indexs = model.fit_transform(data1)
std_data1 = pd.DataFrame(std_indexs,index=data.index,columns=['公共服务','经济收入'])

In [15]:
std_data1.sum(axis=1).sort_values(ascending=False)

地区
上 海         1.166530
四 川         1.160003
江 苏         0.957631
广 东         0.861911
北 京         0.823123
浙 江         0.817148
山 东         0.762966
河 北         0.679049
湖 北         0.648447
辽 宁         0.610893
湖 南         0.583831
黑龙江         0.564482
天 津         0.547992
福 建         0.457258
河 南         0.443192
安 徽         0.391957
云 南         0.379549
广 西         0.368159
山 西         0.354223
陕 西         0.341172
新 疆         0.312840
江 西         0.305040
内蒙古         0.292405
吉 林         0.282199
海 南         0.241106
甘 肃         0.182235
贵 州         0.170200
青 海         0.060959
宁 夏         0.039770
dtype: float64

In [16]:
# 2.练习

In [17]:
data = pd.read_excel('../实验数据/商业银行信用分析.xlsx',index_col=0)

In [18]:
pca_f = PCA(n_components=0.99,svd_solver="full")
data_f = pca_f.fit_transform(data)

In [19]:
data1 = pd.DataFrame(data_f,index=data.index,columns=['经济效益'])

In [20]:
data1.sort_values(by='经济效益',ascending=False)

经济效益
中文名称               
工商银行  133450.817814
建设银行  104771.110728
中国银行  101615.651211
农业银行   97307.685817
交通银行   28080.258530
招商银行   10620.491106
浦发银行    7439.948398
中信银行    6999.538224
民生银行    3763.686801
兴业银行    3064.869544
光大银行    -532.828104
华夏银行   -5626.108215
广发银行   -7913.925930
深发展    -8957.590297
北京银行   -9240.103989
上海银行  -10886.148100
江苏银行  -12367.786989
重庆农商  -14197.391878
恒丰银行  -14303.789842
上海农商  -14401.047576
平安银行  -14418.489746
宁波银行  -14485.418878
渤海银行  -14512.330954
浙商银行  -14842.646985
杭州银行  -14870.605700
徽商银行  -14897.770551
南京银行  -14937.889305
天津银行  -15119.836684
大连银行  -15422.698150
哈尔滨银  -15913.215156
重庆银行  -16086.776353
东莞银行  -16151.902859
锦州银行  -16271.038423
杭州联农  -16429.715760
河北银行  -16466.799525
贵阳银行  -16583.708189
齐鲁银行  -16646.623535
包商银行  -16652.494862
郑州银行  -16655.546441
温州银行  -16696.378666
厦门银行  -16770.543091
日照银行  -16872.404913
德阳银行  -16950.966534
莱商银行  -17006.989182
营口银行  -17024.546810