In [1]:
import numpy as np

In [7]:
#数组和数的运算(广播机制)
a = np.arange(24).reshape(4,6)

In [8]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a-1

array([[-1,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22]])

In [10]:
a*3

array([[ 0,  3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30, 33],
       [36, 39, 42, 45, 48, 51],
       [54, 57, 60, 63, 66, 69]])

In [11]:
a/0 #nan(not a number),inf(infinity)

D:\Anconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Anconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [13]:
#数组和数组的运算(相似数组)
b = np.arange(100,124).reshape(4,6)

In [14]:
b

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [15]:
a + b

array([[100, 102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120, 122],
       [124, 126, 128, 130, 132, 134],
       [136, 138, 140, 142, 144, 146]])

In [16]:
#数组和数组的运算(不相似数组但某一维相同)
c = np.arange(6)

In [17]:
c

array([0, 1, 2, 3, 4, 5])

In [19]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
a - c

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [21]:
c - a

array([[  0,   0,   0,   0,   0,   0],
       [ -6,  -6,  -6,  -6,  -6,  -6],
       [-12, -12, -12, -12, -12, -12],
       [-18, -18, -18, -18, -18, -18]])

In [22]:
d = np.arange(4).reshape(4,1)

In [23]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [24]:
d

array([[0],
       [1],
       [2],
       [3]])

In [25]:
a - d

array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20]])

In [26]:
d - a

array([[  0,  -1,  -2,  -3,  -4,  -5],
       [ -5,  -6,  -7,  -8,  -9, -10],
       [-10, -11, -12, -13, -14, -15],
       [-15, -16, -17, -18, -19, -20]])

In [27]:
#数组和数组的运算(不相似组且无某一维相同)
e = np.arange(10)

In [28]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [29]:
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a - e

ValueError: operands could not be broadcast together with shapes (4,6) (10,) 