In [4]:
import numpy as np
import random

In [8]:
#默认数据类型为
a = np.array([1,2,3])
print(a)
print(type(a))

b = np.array(range(10))
print(b)
print(type(b))

c = np.arange(12)
print(c)
print(type(c))
print(c.dtype)

#float数据类型
d = np.array(range(2,5),dtype="float32")
print(d)
print(d.dtype)

#bool数据类型
e = np.array([1,1,0,0,1,0,1,0],dtype="bool")
print(e)
print(e.dtype)

#调整数据类型
f = e.astype("int8")
print(f)
print(f.dtype)

#小数位数
g = np.array([random.random() for i in range(10)])
print(g)
print(g.dtype)

h = np.round(g,2)
print(h)


[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
int32
[2. 3. 4.]
float32
[ True  True False False  True False  True False]
bool
[1 1 0 0 1 0 1 0]
int8
[0.87191834 0.16536954 0.68054741 0.70987856 0.97878646 0.24757387
 0.34507907 0.47434008 0.83300071 0.26097608]
float64
[0.87 0.17 0.68 0.71 0.98 0.25 0.35 0.47 0.83 0.26]
