In [6]:
import numpy as np

In [7]:
#本地数据读取
us_file_path = "./youtube_video_data/US_video_data_numbers.csv"

uk_file_path = "./youtube_video_data/GB_video_data_numbers.csv"

In [8]:
t1 = np.loadtxt(us_file_path,delimiter=",",dtype="int",unpack=True)

t2 = np.loadtxt(us_file_path,delimiter=",",dtype="int")

In [9]:
t1

array([[4394029, 7860119, 5845909, ...,  142463, 2162240,  515000],
       [ 320053,  185853,  576597, ...,    4231,   41032,   34727],
       [   5931,   26679,   39774, ...,     148,    1384,     195],
       [  46245,       0,  170708, ...,     279,    4737,    4722]])

In [10]:
#修改第1行第2列的值为0(0,1)
t1[0,1] = 0

In [11]:
t1

array([[4394029,       0, 5845909, ...,  142463, 2162240,  515000],
       [ 320053,  185853,  576597, ...,    4231,   41032,   34727],
       [   5931,   26679,   39774, ...,     148,    1384,     195],
       [  46245,       0,  170708, ...,     279,    4737,    4722]])

In [12]:
#将t1中小于10的值修改为3
t1[t1<10]=3

In [13]:
t1

array([[4394029,       3, 5845909, ...,  142463, 2162240,  515000],
       [ 320053,  185853,  576597, ...,    4231,   41032,   34727],
       [   5931,   26679,   39774, ...,     148,    1384,     195],
       [  46245,       3,  170708, ...,     279,    4737,    4722]])

In [14]:
#将t1中小于10的值修改为0，大于10的值修改为1
np.where(t1<=10,0,1)

array([[1, 0, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 1, 1]])

In [16]:
#将t1中小于10的数字替换为10，把大于20的替换为20
t1.clip(10,20) #包不包含10或20无所谓

array([[20, 10, 20, ..., 20, 20, 20],
       [20, 20, 20, ..., 20, 20, 20],
       [20, 20, 20, ..., 20, 20, 20],
       [20, 10, 20, ..., 20, 20, 20]])