In [13]:
import numpy as np

In [14]:
#本地数据读取
us_data = "./youtube_video_data/US_video_data_numbers.csv"

uk_data = "./youtube_video_data/GB_video_data_numbers.csv"

In [15]:
us_data = np.loadtxt(us_data,delimiter=",",dtype="int")

uk_data = np.loadtxt(uk_data,delimiter=",",dtype="int")

In [17]:
#添加国家信息
#构造全为0和1的数据
zeros_data = np.zeros((us_data.shape[0],1)).astype(int)
ones_data = np.ones((uk_data.shape[0],1)).astype(int)

#分别添加一列全为1,0的数组
us_data = np.hstack((us_data,zeros_data)) #hstack为水平拼接
uk_data = np.hstack((uk_data,ones_data))

#拼接两组数据()
final_data = np.vstack((us_data,uk_data)) #vstack为竖直拼接

In [18]:
final_data

array([[4394029,  320053,    5931,   46245,       0],
       [7860119,  185853,   26679,       0,       0],
       [5845909,  576597,   39774,  170708,       0],
       ...,
       [ 109222,    4840,      35,     212,       1],
       [ 626223,   22962,     532,    1559,       1],
       [  99228,    1699,      23,     135,       1]])

In [19]:
#行交换
final_data[[1,2],:] = final_data[[2,1],:] 

In [20]:
final_data

array([[4394029,  320053,    5931,   46245,       0],
       [5845909,  576597,   39774,  170708,       0],
       [7860119,  185853,   26679,       0,       0],
       ...,
       [ 109222,    4840,      35,     212,       1],
       [ 626223,   22962,     532,    1559,       1],
       [  99228,    1699,      23,     135,       1]])

In [21]:
# 列交换
final_data[:,[0,2]] = final_data[:,[2,0]]

In [22]:
final_data

array([[   5931,  320053, 4394029,   46245,       0],
       [  39774,  576597, 5845909,  170708,       0],
       [  26679,  185853, 7860119,       0,       0],
       ...,
       [     35,    4840,  109222,     212,       1],
       [    532,   22962,  626223,    1559,       1],
       [     23,    1699,   99228,     135,       1]])