In [1]:
import numpy as np
import random

In [2]:
#默认数据类型为
a = np.array([1,2,3])
print(a)
print(type(a))
print()

b = np.array(range(10))
print(b)
print(type(b))
print()

c = np.arange(12)
print(c)
print(type(c))
print(c.dtype)
print()

#float数据类型
d = np.array(range(2,5),dtype="float32")
print(d)
print(d.dtype)
print()

#bool数据类型
e = np.array([1,1,0,0,1,0,1,0],dtype="bool")
print(e)
print(e.dtype)
print()

#调整数据类型
f = e.astype("int8")
print(f)
print(f.dtype)
print()

#小数位数
g = np.array([random.random() for i in range(10)])
print(g)
print(g.dtype)
print()

h = np.round(g,2)
print(h)
print()

#多于一个维度
i = np.array([[1,2],[3,4]])
print(i)
print()

#empty创建，numpy.empty(shape, dtype=float, order=‘C’)
j = np.empty([2,2,3],dtype=int)
print(j)
print()

#创建全为0或全为1的数组
print(np.zeros([3,4],dtype=float))
print()
print(np.ones([3,4],dtype=float))
print()

#创建等差数列
print(np.linspace(1,10,20)) #第一个参数为开始，第二个参数为结束，第三个参数为数量

[1 2 3]
<class 'numpy.ndarray'>

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
int32

[2. 3. 4.]
float32

[ True  True False False  True False  True False]
bool

[1 1 0 0 1 0 1 0]
int8

[0.22238214 0.05793557 0.6640203  0.0478009  0.24694503 0.15923657
 0.49171266 0.00970606 0.73888163 0.2432187 ]
float64

[0.22 0.06 0.66 0.05 0.25 0.16 0.49 0.01 0.74 0.24]

[[1 2]
 [3 4]]

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
